<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import SmisTopBar from '@/components/SmisTopBar.vue'
import SmisIcon from '@/components/SmisIcon.vue'
import SmisStatusTag from '@/components/SmisStatusTag.vue'
import { useAuthStore } from '@/stores/auth'
import { getEquipment } from '@/api/smis'
import type { Equipment } from '@/api/types'
import { formatDate } from '@/utils/format'
import { getErrorMessage } from '@/api/supabase'
const auth=useAuthStore();const item=ref<Equipment|null>(null);const loading=ref(true)
async function load(id:string){if(!(await auth.ensureValidSession()))return;try{item.value=await getEquipment(auth.token,id)}catch(e){uni.showToast({title:getErrorMessage(e),icon:'none'})}finally{loading.value=false}}
onLoad((query)=>load(String(query?.id||'')))
</script>
<template><view class="page-shell"><SmisTopBar :title="item?.equipmentName||'设备详情'" :subtitle="item?.equipmentCode" show-back/><view class="page-body detail-body"><view v-if="loading" class="loading"><wd-loading color="#4f46e5"/></view><template v-else-if="item"><view class="identity surface-card"><image v-if="item.photoUrl||item.nameplateUrl" :src="item.photoUrl||item.nameplateUrl||''" mode="aspectFill"/><view v-else class="identity__fallback"><SmisIcon name="equipment" size="72rpx"/></view><view class="identity__copy"><view><SmisStatusTag :status="item.operationStatus"/><SmisStatusTag v-if="item.isSpecialEquipment" status="" label="特种设备"/></view><text>{{item.equipmentName}}</text><text class="small">{{item.category?.categoryName||item.equipmentKind}} · {{item.model||item.specification||'未录入型号'}}</text></view></view><view class="fact-card surface-card"><text class="card-title">设备身份</text><view class="facts"><view><text>设备编号</text><text class="strong">{{item.equipmentCode}}</text></view><view><text>出厂编号</text><text class="strong">{{item.factoryNo||'--'}}</text></view><view><text>注册代码</text><text class="strong">{{item.registrationCode||'--'}}</text></view><view><text>制造厂家</text><text class="strong">{{item.manufacturer||'--'}}</text></view><view><text>启用日期</text><text class="strong">{{formatDate(item.enableDate)}}</text></view><view><text>重要等级</text><text class="strong">{{item.importanceLevel||'--'}}</text></view></view></view><view class="fact-card surface-card"><text class="card-title">责任与位置</text><view class="info-row"><SmisIcon name="location" size="34rpx"/><view><text>安装位置</text><text class="strong">{{item.location?.locationName||item.detailLocation||'--'}}</text></view></view><view class="info-row"><SmisIcon name="organization" size="34rpx"/><view><text>使用组织</text><text class="strong">{{item.usingOrganization?.organizationName||'--'}}</text></view></view><view class="info-row"><SmisIcon name="user" size="34rpx"/><view><text>设备责任人</text><text class="strong">{{item.responsible?.employeeName||'--'}}</text></view></view></view><view class="inspect-card"><view><text>下次检验</text><text class="strong">{{formatDate(item.nextInspectionDueDate)}}</text></view><view><text>历史检验</text><text class="strong">{{item.inspectionCount}} 次</text></view><view><text>相关附件</text><text class="strong">{{item.attachmentCount}} 份</text></view></view><image v-if="item.nameplateUrl" class="nameplate" :src="item.nameplateUrl" mode="widthFix"/></template><view v-else class="loading"><text>设备档案不存在或无权查看</text></view></view></view></template>
<style scoped lang="scss">.detail-body{padding-bottom:50rpx}.loading{min-height:320rpx;display:flex;align-items:center;justify-content:center;color:var(--smis-text-muted)}.identity{margin-top:-42rpx;padding:20rpx;display:flex;gap:20rpx}.identity>image,.identity__fallback{width:172rpx;height:172rpx;border-radius:18rpx;background:#e9f1f6}.identity__fallback{color:var(--smis-primary);display:flex;align-items:center;justify-content:center}.identity__copy{min-width:0;flex:1;display:flex;flex-direction:column;justify-content:center}.identity__copy>view{display:flex;gap:8rpx}.identity__copy>text{margin-top:14rpx;font-size:29rpx;font-weight:700}.identity__copy>.small{margin-top:7rpx;color:var(--smis-text-muted);font-size:21rpx;line-height:1.4}.fact-card{margin-top:18rpx;padding:26rpx}.card-title{display:block;margin-bottom:18rpx;font-size:28rpx;font-weight:700}.facts{display:grid;grid-template-columns:1fr 1fr;gap:22rpx 18rpx}.facts>view{display:flex;flex-direction:column}.facts text,.info-row text{font-size:20rpx;color:var(--smis-text-muted)}.facts .strong,.info-row .strong{margin-top:6rpx;font-size:23rpx;font-weight:600;line-height:1.4}.info-row{min-height:88rpx;display:flex;align-items:center;gap:16rpx;color:var(--smis-primary)}.info-row+ .info-row{border-top:1rpx solid var(--smis-line)}.info-row>view{min-width:0;flex:1;display:flex;flex-direction:column;color:var(--smis-text)}.inspect-card{margin-top:18rpx;padding:25rpx;border-radius:22rpx;background:#211d59;color:#fff;display:grid;grid-template-columns:repeat(3,1fr)}.inspect-card>view{display:flex;flex-direction:column;align-items:center}.inspect-card>view+view{border-left:1rpx solid rgba(255,255,255,.14)}.inspect-card text{font-size:19rpx;opacity:.62}.inspect-card .strong{margin-top:9rpx;font-size:23rpx}.nameplate{width:100%;margin-top:18rpx;border-radius:20rpx;background:#fff}</style>
