<script setup lang="ts">
import { ref } from 'vue'
import { onLoad, onPullDownRefresh, onShow } from '@dcloudio/uni-app'
import SmisTopBar from '@/components/SmisTopBar.vue'
import SmisIcon from '@/components/SmisIcon.vue'
import SmisStatusTag from '@/components/SmisStatusTag.vue'
import SmisEmpty from '@/components/SmisEmpty.vue'
import { useAuthStore } from '@/stores/auth'
import { useDictionaryStore } from '@/stores/dictionary'
import { listEquipment } from '@/api/smis'
import type { Equipment, EquipmentOverview } from '@/api/types'
import { getErrorMessage } from '@/api/supabase'

const auth=useAuthStore();const dictionary=useDictionaryStore();const keyword=ref('');const rows=ref<Equipment[]>([]);const loading=ref(false);const overview=ref<EquipmentOverview>({total:0,inUse:0,boilerCount:0,dueSoon:0})
async function load(){if(!(await auth.ensureValidSession()))return;loading.value=true;try{const data=await listEquipment(auth.token,{keyword:keyword.value,to:49});rows.value=data.records;overview.value=data.overview}catch(e){uni.showToast({title:getErrorMessage(e),icon:'none'})}finally{loading.value=false;uni.stopPullDownRefresh()}}
function label(value:string,typeCodes:string[]){return dictionary.labelAny(typeCodes,value,value)}
function openDetail(id:string){uni.navigateTo({url:`/pages/equipment/detail?id=${id}`})}
onShow(load);onLoad(()=>dictionary.load(auth.token));onPullDownRefresh(load)
</script>
<template><view class="page-shell"><SmisTopBar title="设备台账" eyebrow="EQUIPMENT LEDGER" subtitle="状态、位置与检验周期" show-back/><view class="page-body ledger-body"><view class="overview"><view><text>{{overview.total}}</text><text class="small">设备总数</text></view><view><text>{{overview.inUse}}</text><text class="small">在用</text></view><view class="overview__alert"><text>{{overview.dueSoon}}</text><text class="small">临近检验</text></view></view><view class="search"><SmisIcon name="search" size="34rpx"/><input v-model="keyword" type="search" name="equipment-search" aria-label="搜索设备台账" autocomplete="off" placeholder="设备编号 / 名称 / 型号" confirm-type="search" @confirm="load"/><button @tap="load">查询</button></view><view v-if="loading" class="loading"><wd-loading color="#4f46e5"/><text>正在读取设备档案…</text></view><view v-else-if="rows.length" class="equipment-list"><button v-for="item in rows" :key="item.id" class="equipment surface-card" @tap="openDetail(item.id)"><view class="equipment__top"><view class="equipment__icon"><SmisIcon name="equipment" size="40rpx"/></view><view class="equipment__copy"><text class="line-clamp-2">{{item.equipmentName}}</text><text class="small">{{item.equipmentCode}}</text></view><SmisStatusTag :status="item.operationStatus"/></view><view class="equipment__spec"><text>{{item.category?.categoryName||label(item.equipmentKind,['smisEquipmentKind'])}}</text><view class="i"/><text>{{item.model||item.specification||'型号未录入'}}</text></view><view class="equipment__location"><SmisIcon name="location" size="28rpx"/><text class="line-clamp-2">{{item.location?.locationName||item.detailLocation||'位置未录入'}}</text></view><view class="equipment__foot"><text>{{label(item.useStatus,['smisEquipmentUseStatus'])}}</text><text v-if="item.isSpecialEquipment" class="special">特种设备</text><SmisIcon name="chevron" size="28rpx"/></view></button></view><SmisEmpty v-else title="未找到设备" description="请调整关键词或在 Web 端维护设备档案"/></view></view></template>
<style scoped lang="scss">.ledger-body{padding-bottom:50rpx}.overview{margin-top:-42rpx;padding:25rpx;border-radius:22rpx;background:#fff;box-shadow:var(--smis-shadow);display:grid;grid-template-columns:repeat(3,1fr)}.overview>view{display:flex;flex-direction:column;align-items:center}.overview>view+view{border-left:1rpx solid var(--smis-line)}.overview text{font-size:36rpx;font-weight:700;color:var(--smis-primary)}.overview .small{margin-top:5rpx;color:var(--smis-text-muted);font-size:19rpx}.overview__alert text{color:var(--smis-warning)}.search{height:88rpx;margin-top:22rpx;padding-left:22rpx;border-radius:20rpx;background:#fff;color:var(--smis-text-muted);display:flex;align-items:center;gap:14rpx}.search input{min-width:0;flex:1;font-size:24rpx}.search button{height:70rpx;margin:0 9rpx 0 0;padding:0 26rpx;border-radius:16rpx;background:var(--smis-primary);color:#fff;font-size:22rpx}.loading{height:320rpx;display:flex;align-items:center;justify-content:center;gap:14rpx;color:var(--smis-text-secondary)}.equipment-list{margin-top:20rpx}.equipment{width:100%;margin:0 0 16rpx;padding:24rpx;text-align:left}.equipment__top{display:flex;align-items:flex-start;gap:16rpx}.equipment__icon{width:64rpx;height:64rpx;border-radius:19rpx;background:var(--smis-primary-soft);color:var(--smis-primary);display:flex;align-items:center;justify-content:center}.equipment__copy{min-width:0;flex:1;display:flex;flex-direction:column}.equipment__copy text{font-size:27rpx;font-weight:700;line-height:1.4}.equipment__copy .small{margin-top:4rpx;color:var(--smis-text-muted);font-size:20rpx}.equipment__spec{margin:18rpx 0 0 80rpx;display:flex;align-items:center;gap:12rpx;color:var(--smis-text-secondary);font-size:21rpx}.equipment__spec .i{width:1rpx;height:22rpx;background:var(--smis-line)}.equipment__location{margin-top:18rpx;padding:14rpx 16rpx;border-radius:14rpx;background:#f5f8fa;color:var(--smis-text-secondary);font-size:21rpx;display:flex;gap:9rpx}.equipment__foot{margin-top:18rpx;padding-top:16rpx;border-top:1rpx solid var(--smis-line);display:flex;align-items:center;gap:10rpx;color:var(--smis-text-muted);font-size:20rpx}.equipment__foot text:first-child{flex:1}.special{padding:7rpx 12rpx;border-radius:999rpx;background:#fff1df;color:var(--smis-warning);font-weight:700}</style>
