<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import SmisBottomNav from '@/components/SmisBottomNav.vue'
import SmisTopBar from '@/components/SmisTopBar.vue'
import SmisIcon from '@/components/SmisIcon.vue'
import { useAuthStore } from '@/stores/auth'
import { listHazards, listRiskTasks } from '@/api/smis'
import { formatDate } from '@/utils/format'
const auth=useAuthStore();const loading=ref(false);const rows=ref<Array<{id:string;type:string;title:string;body:string;time:string;url:string}>>([])
const grouped=computed(()=>rows.value)
async function load(){if(!(await auth.ensureValidSession()))return;loading.value=true;try{const [risk,hazard]=await Promise.all([listRiskTasks(auth.token,{status:'overdue',to:9}),listHazards(auth.token,{status:'pending_acceptance',to:9})]);rows.value=[...risk.records.map(x=>({id:x.id,type:'逾期提醒',title:x.riskPointName,body:`风险巡查 ${x.taskNo} 已超过计划时间`,time:x.plannedEndAt,url:`/pages/risk/detail?id=${x.id}`})),...hazard.records.map(x=>({id:x.id,type:'待验收',title:x.description,body:`隐患 ${x.hazardNo} 已提交整改，请及时验收`,time:x.rectificationCompletedAt||x.reportedAt,url:`/pages/hazards/detail?id=${x.id}`}))].sort((a,b)=>+new Date(b.time)-+new Date(a.time))}finally{loading.value=false}}
function open(url:string){uni.navigateTo({url})}
onShow(load)
</script>
<template><view class="page-shell"><SmisTopBar title="安全消息" eyebrow="SAFETY NOTICE" subtitle="只聚焦需要你处理的变化"/><view class="page-body"><view v-if="loading" class="state"><wd-loading color="#4f46e5"/><text>正在读取提醒…</text></view><view v-else-if="grouped.length" class="message-list"><button v-for="item in grouped" :key="`${item.type}-${item.id}`" class="message surface-card" @tap="open(item.url)"><view class="message__icon"><SmisIcon name="notice" size="38rpx"/></view><view class="message__copy"><view><text>{{item.type}}</text><text class="small">{{formatDate(item.time,true)}}</text></view><text class="strong line-clamp-2">{{item.title}}</text><text class="paragraph line-clamp-2">{{item.body}}</text></view><SmisIcon name="chevron" size="28rpx"/></button></view><view v-else class="state surface-card"><view class="state__safe"><SmisIcon name="check" size="50rpx"/></view><text>没有待处理消息</text><text class="small">逾期任务和待验收隐患会出现在这里</text></view></view><SmisBottomNav active="messages"/></view></template>
<style scoped lang="scss">.message-list{display:flex;flex-direction:column;gap:16rpx}.message{width:100%;margin:0;padding:24rpx;text-align:left;display:flex;align-items:center;gap:18rpx}.message__icon{width:66rpx;height:66rpx;border-radius:20rpx;background:#fff1df;color:var(--smis-warning);display:flex;align-items:center;justify-content:center}.message__copy{min-width:0;flex:1;display:flex;flex-direction:column}.message__copy>view{display:flex;justify-content:space-between;gap:12rpx}.message__copy>view text{font-size:20rpx;color:var(--smis-warning);font-weight:700}.message__copy .small{color:var(--smis-text-muted);font-size:18rpx}.message__copy .strong{margin-top:8rpx;font-size:26rpx}.message__copy .paragraph{margin:5rpx 0 0;color:var(--smis-text-secondary);font-size:21rpx;line-height:1.45}.state{min-height:360rpx;padding:60rpx;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14rpx;color:var(--smis-text-secondary)}.state__safe{width:86rpx;height:86rpx;border-radius:26rpx;background:#e5f3ec;color:var(--smis-success);display:flex;align-items:center;justify-content:center}.state>text{font-size:27rpx;font-weight:700}.state>.small{font-size:21rpx;color:var(--smis-text-muted);text-align:center}</style>
