<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import SmisTopBar from '@/components/SmisTopBar.vue'
import SmisIcon from '@/components/SmisIcon.vue'
import SmisEmpty from '@/components/SmisEmpty.vue'
import { useAuthStore } from '@/stores/auth'
import { useProfileStore } from '@/stores/profile'
import { getShiftCalendar } from '@/api/smis'
import type { ShiftAssignment } from '@/api/types'
import { currentMonth, monthLabel } from '@/utils/format'
import { getErrorMessage } from '@/api/supabase'
const auth=useAuthStore();const profile=useProfileStore();const month=ref(currentMonth());const rows=ref<ShiftAssignment[]>([]);const loading=ref(false)
const days=computed(()=>{const parts=month.value.split('-').map(Number);const y=parts[0]||new Date().getFullYear();const m=parts[1]||1;const count=new Date(y,m,0).getDate();const first=new Date(y,m-1,1).getDay();return [...Array(first).fill(null),...Array.from({length:count},(_,i)=>i+1)]})
const rowMap=computed(()=>Object.fromEntries(rows.value.map(x=>[Number(x.workDate.slice(-2)),x])))
const upcoming=computed(()=>rows.value.filter(x=>new Date(`${x.workDate}T23:59:59`)>=new Date()).slice(0,4))
async function load(){if(!(await auth.ensureValidSession()))return;loading.value=true;try{await profile.load(auth.token);if(!profile.profile?.employeeId){rows.value=[];return}const data=await getShiftCalendar(auth.token,profile.profile.employeeId,month.value);rows.value=data?.assignments||[]}catch(e){uni.showToast({title:getErrorMessage(e),icon:'none'})}finally{loading.value=false}}
function changeMonth(delta:number){const parts=month.value.split('-').map(Number);const y=parts[0]||new Date().getFullYear();const m=parts[1]||1;const d=new Date(y,m-1+delta,1);month.value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;load()}
onShow(load)
</script>
<template><view class="page-shell"><SmisTopBar title="我的排班" eyebrow="SHIFT CALENDAR" subtitle="班次、休假与跨日安排" show-back/><view class="page-body schedule-body"><view class="calendar surface-card"><view class="calendar__head"><button aria-label="上个月" @tap="changeMonth(-1)"><SmisIcon name="back" size="32rpx"/></button><view><text>{{monthLabel(month)}}</text><text class="small">{{profile.profile?.employeeName||'当前员工'}}</text></view><button aria-label="下个月" @tap="changeMonth(1)"><SmisIcon name="chevron" size="32rpx"/></button></view><view class="week"><text v-for="x in ['日','一','二','三','四','五','六']" :key="x">{{x}}</text></view><view class="days"><view v-for="(day,index) in days" :key="`${day}-${index}`" class="day" :class="{'day--empty':!day,'day--shift':day&&rowMap[day],'day--leave':day&&rowMap[day]?.assignmentStatus==='leave','day--worked':day&&rowMap[day]?.assignmentStatus==='worked'}"><text v-if="day">{{day}}</text><text class="small" v-if="day&&rowMap[day]">{{rowMap[day].shiftName.slice(0,3)}}</text></view></view><view class="legend"><text><view class="i scheduled"/>排班</text><text><view class="i worked"/>已出勤</text><text><view class="i leave"/>休假</text></view></view><view class="section-head"><text>近期班次</text><text class="small">时间以排班计划为准</text></view><view v-if="loading" class="loading"><wd-loading color="#4f46e5"/></view><view v-else-if="upcoming.length" class="shift-list"><view v-for="item in upcoming" :key="item.id" class="shift surface-card"><view class="shift__date"><text>{{Number(item.workDate.slice(-2))}}</text><text class="small">{{Number(item.workDate.slice(5,7))}}月</text></view><view class="shift__copy"><text>{{item.shiftName}}</text><text class="small">{{item.startTime.slice(0,5)}} — {{item.endTime.slice(0,5)}}{{item.crossDay?' · 跨日':''}}</text><text class="paragraph" v-if="item.remark">{{item.remark}}</text></view><text class="shift__type">{{item.shiftType}}</text></view></view><SmisEmpty v-else title="本月暂无排班" description="排班由 Web 端统一维护，发布后会自动同步到这里"/></view></view></template>
<style scoped lang="scss">.schedule-body{padding-bottom:50rpx}.calendar{margin-top:-42rpx;padding:25rpx}.calendar__head{display:grid;grid-template-columns:70rpx 1fr 70rpx;align-items:center}.calendar__head button{width:70rpx;height:70rpx;margin:0;padding:0;border-radius:18rpx;background:#f0f4f6;color:var(--smis-primary);display:flex;align-items:center;justify-content:center}.calendar__head>view{display:flex;flex-direction:column;align-items:center}.calendar__head text{font-size:30rpx;font-weight:700}.calendar__head .small{margin-top:4rpx;color:var(--smis-text-muted);font-size:19rpx}.week,.days{display:grid;grid-template-columns:repeat(7,1fr)}.week{margin-top:22rpx;padding-bottom:10rpx;border-bottom:1rpx solid var(--smis-line)}.week text{text-align:center;color:var(--smis-text-muted);font-size:19rpx}.days{gap:8rpx 3rpx;margin-top:10rpx}.day{height:76rpx;border-radius:15rpx;display:flex;flex-direction:column;align-items:center;justify-content:center}.day>text{font-size:23rpx}.day .small{font-size:16rpx;margin-top:2rpx}.day--shift{background:#eef2ff;color:var(--smis-primary)}.day--worked{background:#e4f2eb;color:var(--smis-success)}.day--leave{background:#fff1df;color:var(--smis-warning)}.legend{margin-top:20rpx;padding-top:16rpx;border-top:1rpx solid var(--smis-line);display:flex;justify-content:center;gap:24rpx}.legend text{display:flex;align-items:center;gap:7rpx;color:var(--smis-text-muted);font-size:18rpx}.legend .i{width:14rpx;height:14rpx;border-radius:4rpx}.legend .scheduled{background:#9dbfd5}.legend .worked{background:#76ba9c}.legend .leave{background:#e9b076}.section-head{margin:30rpx 4rpx 16rpx;display:flex;align-items:flex-end;justify-content:space-between}.section-head text{font-size:29rpx;font-weight:700}.section-head .small{font-size:19rpx;color:var(--smis-text-muted)}.loading{height:220rpx;display:flex;align-items:center;justify-content:center}.shift-list{display:flex;flex-direction:column;gap:14rpx}.shift{padding:22rpx;display:flex;align-items:center;gap:18rpx}.shift__date{width:66rpx;height:72rpx;border-radius:17rpx;background:#eef2ff;color:var(--smis-primary);display:flex;flex-direction:column;align-items:center;justify-content:center}.shift__date text{font-size:27rpx;font-weight:700}.shift__date .small{font-size:17rpx}.shift__copy{min-width:0;flex:1;display:flex;flex-direction:column}.shift__copy>text{font-size:25rpx;font-weight:700}.shift__copy .small{margin-top:5rpx;color:var(--smis-text-secondary);font-size:20rpx}.shift__copy .paragraph{margin:5rpx 0 0;color:var(--smis-text-muted);font-size:18rpx}.shift__type{padding:8rpx 12rpx;border-radius:999rpx;background:#f0f4f6;color:var(--smis-text-secondary);font-size:18rpx}</style>
