<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app'
import SmisBottomNav from '@/components/SmisBottomNav.vue'
import SmisIcon from '@/components/SmisIcon.vue'
import { useAuthStore } from '@/stores/auth'
import { useProfileStore } from '@/stores/profile'
const auth=useAuthStore();const profile=useProfileStore()
async function load(){if(await auth.ensureValidSession())await profile.load(auth.token,true)}
function logout(){uni.showModal({title:'退出登录',content:'退出后需要重新验证账号，是否继续？',confirmText:'退出',success:r=>{if(r.confirm)auth.logout()}})}
function open(url:string){uni.navigateTo({url})}
function showPermission(){uni.showToast({title:'数据与 Web 端权限同步',icon:'none'})}
onShow(load)
</script>
<template><view class="page-shell"><view class="profile-hero"><view class="profile-hero__avatar">{{(profile.profile?.employeeName||'安').slice(-1)}}</view><view class="profile-hero__copy"><text>{{profile.profile?.employeeName||'安全生产用户'}}</text><text class="small">{{profile.profile?.employeeNo||auth.user?.email||auth.user?.phone||'账号已登录'}}</text></view><view class="profile-hero__status"><view class="i"/>在岗</view></view><view class="page-body mine-body"><view class="identity surface-card"><view><text>所属组织</text><text class="strong">{{profile.profile?.organizationName||'未绑定组织'}}</text></view><view><text>联系电话</text><text class="strong">{{profile.profile?.phone||'--'}}</text></view></view><view class="menu surface-card"><button @tap="open('/pages/schedule/index')"><view><SmisIcon name="schedule" size="38rpx"/></view><text>我的排班</text><SmisIcon name="chevron" size="28rpx"/></button><button @tap="open('/pages/messages/index')"><view><SmisIcon name="message" size="38rpx"/></view><text>安全消息</text><SmisIcon name="chevron" size="28rpx"/></button><button @tap="showPermission"><view><SmisIcon name="shield" size="38rpx"/></view><text>账号与权限</text><SmisIcon name="chevron" size="28rpx"/></button></view><view v-if="profile.profile && !profile.profile.isEmployeeLinked" class="link-warning"><SmisIcon name="notice" size="34rpx"/><text>当前账号未关联员工档案，排班与现场任务可能不可用，请联系管理员在 Web 端绑定。</text></view><button class="logout" @tap="logout">退出登录</button><text class="version">SMIS Mobile · v0.1.0</text></view><SmisBottomNav active="mine"/></view></template>
<style scoped lang="scss">.profile-hero{padding:calc(46rpx + env(safe-area-inset-top)) 32rpx 58rpx;background:var(--smis-hero-gradient);color:#fff;display:flex;align-items:center;gap:22rpx}.profile-hero__avatar{width:104rpx;height:104rpx;border:5rpx solid rgba(255,255,255,.18);border-radius:32rpx;background:#f5b942;color:#493200;font-size:42rpx;font-weight:700;display:flex;align-items:center;justify-content:center}.profile-hero__copy{min-width:0;flex:1;display:flex;flex-direction:column}.profile-hero__copy text{font-size:35rpx;font-weight:700}.profile-hero__copy .small{margin-top:9rpx;font-size:22rpx;opacity:.68}.profile-hero__status{padding:10rpx 16rpx;border-radius:999rpx;background:rgba(255,255,255,.10);font-size:20rpx;display:flex;align-items:center;gap:8rpx}.profile-hero__status .i{width:10rpx;height:10rpx;border-radius:50%;background:#60d09b}.mine-body{margin-top:-28rpx;position:relative}.identity{padding:26rpx;display:grid;grid-template-columns:1fr 1fr;gap:24rpx}.identity>view{display:flex;flex-direction:column}.identity text{font-size:21rpx;color:var(--smis-text-muted)}.identity .strong{margin-top:8rpx;font-size:25rpx}.menu{margin-top:20rpx;overflow:hidden}.menu button{width:100%;min-height:102rpx;margin:0;padding:0 24rpx;border-radius:0;background:#fff;text-align:left;display:flex;align-items:center;gap:18rpx}.menu button+button{border-top:1rpx solid var(--smis-line)}.menu button>view{width:58rpx;height:58rpx;border-radius:18rpx;background:var(--smis-primary-soft);color:var(--smis-primary);display:flex;align-items:center;justify-content:center}.menu button>text{flex:1;font-size:25rpx;font-weight:600}.link-warning{margin-top:20rpx;padding:22rpx;border-radius:18rpx;background:#fff1df;color:#91551e;display:flex;align-items:flex-start;gap:14rpx;font-size:21rpx;line-height:1.5}.logout{width:100%;min-height:94rpx;margin-top:28rpx;border-radius:20rpx;background:#fff;color:var(--smis-danger);font-size:26rpx;font-weight:700}.version{display:block;margin-top:24rpx;text-align:center;color:var(--smis-text-muted);font-size:19rpx}</style>
