<script setup lang="ts">
import { ref } from 'vue'
import { onPullDownRefresh, onShow } from '@dcloudio/uni-app'
import SmisTopBar from '@/components/SmisTopBar.vue'
import SmisStatusTag from '@/components/SmisStatusTag.vue'
import SmisEmpty from '@/components/SmisEmpty.vue'
import SmisIcon from '@/components/SmisIcon.vue'
import { useAuthStore } from '@/stores/auth'
import { listHazards } from '@/api/smis'
import type { HazardOverview, HazardRecord, HazardStatus } from '@/api/types'
import { formatDate, hazardLevelBadge } from '@/utils/format'
import { getErrorMessage } from '@/api/supabase'
const auth=useAuthStore();const loading=ref(false);const keyword=ref('');const status=ref<HazardStatus|''>('');const rows=ref<HazardRecord[]>([]);const overview=ref<HazardOverview>({total:0,pendingApproval:0,rectifying:0,pendingAcceptance:0,completed:0,closed:0})
const tabs:Array<{value:HazardStatus|'';label:string}>=[{value:'',label:'全部'},{value:'pending_approval',label:'待核准'},{value:'rectifying',label:'整改中'},{value:'pending_acceptance',label:'待验收'},{value:'completed',label:'已完成'}]
async function load(){if(!(await auth.ensureValidSession()))return;loading.value=true;try{const data=await listHazards(auth.token,{status:status.value,keyword:keyword.value,to:49});rows.value=data.records;overview.value=data.overview}catch(e){uni.showToast({title:getErrorMessage(e),icon:'none'})}finally{loading.value=false;uni.stopPullDownRefresh()}}
function select(value:HazardStatus|''){status.value=value;load()}
function openDetail(id:string){uni.navigateTo({url:`/pages/hazards/detail?id=${id}`})}
onShow(load);onPullDownRefresh(load)
</script>
<template><view class="page-shell"><SmisTopBar title="隐患治理" eyebrow="HAZARD CLOSURE" subtitle="从上报到验收，全程可追溯" show-back/><view class="page-body hazard-body"><view class="overview"><view><text class="strong">{{overview.total}}</text><text>全部隐患</text></view><view><text class="strong">{{overview.rectifying}}</text><text>整改中</text></view><view class="overview__alert"><text class="strong">{{overview.pendingAcceptance}}</text><text>待验收</text></view></view><view class="search"><SmisIcon name="search" size="32rpx"/><input v-model="keyword" type="search" name="hazard-search" aria-label="搜索隐患编号" autocomplete="off" placeholder="搜索隐患编号" confirm-type="search" @confirm="load"/><button @tap="load">查询</button></view><scroll-view class="tabs" scroll-x :show-scrollbar="false"><button v-for="tab in tabs" :key="tab.value" :class="{'active':status===tab.value}" @tap="select(tab.value)">{{tab.label}}</button></scroll-view><view v-if="loading" class="loading"><wd-loading color="#4f46e5"/><text>正在同步隐患台账…</text></view><view v-else-if="rows.length" class="hazard-list"><button v-for="item in rows" :key="item.id" class="hazard surface-card" @tap="openDetail(item.id)"><view class="hazard__head"><view class="hazard__level">{{hazardLevelBadge(item.hazardLevel)}}</view><view><text>{{item.hazardNo}}</text><text class="small">{{formatDate(item.reportedAt,true)}}</text></view><SmisStatusTag :status="item.status"/></view><text class="hazard__desc line-clamp-2">{{item.description}}</text><view class="hazard__place"><SmisIcon name="location" size="27rpx"/><text class="line-clamp-2">{{item.location}}</text></view><view class="hazard__foot"><text>上报：{{item.reporterEmployeeName}}</text><text v-if="item.rectificationResponsibleEmployeeName">整改：{{item.rectificationResponsibleEmployeeName}}</text><SmisIcon name="chevron" size="28rpx"/></view></button></view><SmisEmpty v-else title="暂无隐患记录" description="现场发现问题，可通过底部“随手拍”立即上报"/></view></view></template>
<style scoped lang="scss">.hazard-body{padding-top:0;padding-bottom:50rpx}.overview{margin:-38rpx 0 20rpx;padding:24rpx;border-radius:22rpx;background:#fff;box-shadow:var(--smis-shadow);display:grid;grid-template-columns:repeat(3,1fr)}.overview>view{display:flex;flex-direction:column;align-items:center}.overview>view+view{border-left:1rpx solid var(--smis-line)}.overview .strong{font-size:35rpx;color:var(--smis-primary)}.overview text{margin-top:5rpx;color:var(--smis-text-muted);font-size:19rpx}.overview__alert .strong{color:var(--smis-warning)}.search{height:82rpx;padding-left:20rpx;border-radius:19rpx;background:#fff;color:var(--smis-text-muted);display:flex;align-items:center;gap:12rpx}.search input{min-width:0;flex:1;font-size:23rpx}.search button{height:64rpx;margin:0 9rpx 0 0;padding:0 22rpx;border-radius:14rpx;background:var(--smis-primary);color:#fff;font-size:21rpx}.tabs{width:100%;white-space:nowrap;margin:18rpx 0}.tabs button{display:inline-flex;min-width:118rpx;height:66rpx;margin:0 12rpx 0 0;padding:0 22rpx;border-radius:999rpx;background:#fff;color:var(--smis-text-secondary);align-items:center;justify-content:center;font-size:21rpx}.tabs .active{background:var(--smis-hero-gradient);color:#fff}.loading{height:280rpx;display:flex;align-items:center;justify-content:center;gap:14rpx;color:var(--smis-text-secondary)}.hazard-list{display:flex;flex-direction:column;gap:16rpx}.hazard{width:100%;margin:0;padding:24rpx;text-align:left}.hazard__head{display:flex;align-items:center;gap:14rpx}.hazard__level{width:58rpx;height:58rpx;border-radius:17rpx;background:#fff1df;color:var(--smis-warning);font-size:26rpx;font-weight:700;display:flex;align-items:center;justify-content:center}.hazard__head>view:nth-child(2){min-width:0;flex:1;display:flex;flex-direction:column}.hazard__head>view text{font-size:23rpx;font-weight:700}.hazard__head .small{margin-top:4rpx;color:var(--smis-text-muted);font-size:18rpx}.hazard__desc{display:block;margin-top:17rpx;font-size:27rpx;line-height:1.5;font-weight:700}.hazard__place{margin-top:14rpx;color:var(--smis-text-secondary);font-size:21rpx;display:flex;gap:8rpx}.hazard__foot{margin-top:18rpx;padding-top:15rpx;border-top:1rpx solid var(--smis-line);color:var(--smis-text-muted);font-size:19rpx;display:flex;align-items:center;gap:13rpx}.hazard__foot text:first-child{flex:1}</style>
